package TP1;

import java.util.*;

public class WeightedGraph {

    /**
     * Integer : ID of Node
     * Node : Object Node
     */
    Map<Integer, Node> nodes;

    public WeightedGraph () {
        nodes = new HashMap<Integer, Node>();
    }


    /**
     * Public function that generates the graph recursively
     *
     * @param graphInformation information originating from txt file, in which each line represents either
     *                         information pertaining to node, or information pertaining to edge
     */
    public void createGraph(List<String> graphInformation) {
        createGraph(graphInformation, 0);
    }

    /**
     * Private helper function that recursively process information generated by reading a text file and creates nodes, or
     * edges depending on the information read
     *
     * @param graphInformation list of either information pertaining to the creation of the node (index, hasRecharge; size = 2)
     *                         or information pertaining to edge (source, destination, weight)
     *
     * @param lineNumber index of information
     * @return
     */
    private void createGraph(List<String> graphInformation, int lineNumber) {
        if (lineNumber == graphInformation.size()) {
            return;
        }
        String[] infoLine = graphInformation.get(lineNumber).split(",");
        if (infoLine.length == 2) {
            boolean hasRecharge = !infoLine[1].equals("0");
            int nodeId = Integer.parseInt(infoLine[0]);
            addNode(new Node(nodeId, hasRecharge));
            createGraph(graphInformation, lineNumber + 1);
        }
        else if (infoLine.length == 3) {
            Node sourceNode = nodes.get(Integer.parseInt(infoLine[0]));
            Node destinationNode = nodes.get(Integer.parseInt(infoLine[1]));
            int minutesWeight = Integer.parseInt(infoLine[2]);
            sourceNode.addEdge(new Edge(sourceNode, destinationNode, minutesWeight));
            destinationNode.addEdge(new Edge(destinationNode, sourceNode, minutesWeight));
            createGraph(graphInformation, lineNumber + 1);
        }
        else {
            createGraph(graphInformation, lineNumber + 1);
        }
    }

    /**
     * Prints the weighted graph in order (Current Node, boolean containsRecharge, and list of neighbors)
     */
    public void printGraph() {
        for (Map.Entry<Integer, Node> entry : nodes.entrySet()) {
            Node currentNode = entry.getValue();
            System.out.print("(Node " + entry.getKey() + ", Has recharge : " + currentNode.hasRecharge + " (");
            for (Edge edge : currentNode.edges) {
                System.out.print("(Neighbor: Node " + edge.destination.index + ", Weight: " + edge.weight + "),");
            }
            System.out.print(")))");
            System.out.println();
        }
    }
    public void addNode(Node newNode) {
        nodes.put(newNode.index, newNode);
    }


    public Collection<Node> plusCourtChemin(Node source, Node destination) {
        return null;
    }

    public void traiterRequetes(String fileName) {

    }

    static class Node {
        private int index;
        private boolean hasRecharge;
        Set<Edge> edges;

        public Node (int index, boolean hasRecharge) {
            edges = new HashSet<>();
            this.index = index;
            this.hasRecharge = hasRecharge;
        }

        public boolean addEdge(Edge newEdge) {
            return edges.add(newEdge);
        }
    }

    static class Edge {
        private Node source;
        private Node destination;
        int weight;

        public Edge (Node source, Node destination, int weight) {
            this.source = source;
            this.destination = destination;
            this.weight = weight;
        }

    }
    
}
